port: 8080
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    include-exception: true
    include-message: always
logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  config:
    import: vault://
  application:
    name: hello-social-auth
  cloud:
    vault:
      uri: http://localhost:8200
      kv:
        enabled: true
        backend: kv
        default-context: secret/hello-social-auth
  data:
    mongodb:
      database: hello
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope: openid,profile,email
          github:
            client-id: ${github.client-id}
            client-secret: ${github.client-secret}
            scope: read:user, user:email
steam:
  api:
    key: ${steam.api-key}