port: 8080
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    include-exception: true
    include-message: always
logging:
  level:
    com:
      emanuel:
        hello:
          processor: INFO
    org:
      springframework:
        vault: DEBUG
        cloud:
          vault: DEBUG
        web:
          client:
            RestTemplate: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  config:
    import: vault://
  application:
    name: hello-social-auth
  cloud:
    vault:
      uri: http://localhost:8200
      kv:
        enabled: true
        backend: kv
        default-context: secret/hello-social-auth
  data:
    mongodb:
      database: hello
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope: openid,profile,email
          github:
            client-id: ${github.client-id}
            client-secret: ${github.client-secret}
            scope: read:user, user:email
          facebook:
            client-id: ${facebook.client-id}
            client-secret: ${facebook.client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: public_profile,email
          okta:
            client-id: ${okta.client-id}
            client-secret: ${okta.client-secret}
            scope: openid, profile, email
            provider: okta
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v11.0/dialog/oauth
            token-uri: https://graph.facebook.com/v11.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id
          okta:
            issuer-uri: https://dev-13mcl0jb443tbcvk.us.auth0.com/
steam:
  api:
    key: ${steam.api-key}