port: 8080
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    include-exception: true
    include-message: always
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  application:
    name: hello-social-auth
  data:
    mongodb:
      database: hello
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <GOOGLE_ID>
            client-secret: <GOOGLE_SECRET>
            scope: openid,profile,email
          github:
            client-id: <GITHUB_ID>
            client-secret: <GITHUB_SECRET>
            scope: read:user, user:email
steam:
  api:
    key: <STEAM_KEY>