server:
  forward-headers-strategy: framework
  port: 8080
  error:
    whitelabel.enabled: false
    include-stacktrace: always
    include-exception: true
    include-message: always
logging:
  level:
    com.emanuel.hello.processor: INFO
    org:
      springframework:
        security: DEBUG
        web.client.RestTemplate: DEBUG
        data.mongodb.core.MongoTemplate: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: replace-me
            client-secret: replace-me
  data:
    strategy: IN_MEMORY
steam:
  api:
    key: replace-me